apiVersion: apps/v1
kind: Deployment
metadata:
  name: livraison-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: livraison-front
  template:
    metadata:
      labels:
        app: livraison-front
    spec:
      containers:
        - name: livraison-front
          image: dali05/livraison-front:latest
          ports:
            - containerPort: 80
